name: bitwit_shit
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  bonfire: ^3.14.0
  audioplayers: ^6.4.0
  breez_liquid:
    git:
      url: https://github.com/breez/breez-sdk-liquid-dart
      ref: v0.9.2-rc1
  flutter_breez_liquid:
    git:
      url: https://github.com/breez/breez-sdk-liquid-flutter
      ref: 5f4a675d6084e06e0e6659e6f783eecbfc92c58a
  logging: ^1.3.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.0.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4
  bip39: ^1.0.6
  path: ^1.9.1
  flutter_fgbg: ^0.7.1
  flutter_app_group_directory: ^1.1.0
  flutter_rust_bridge: 2.9.0
  another_flushbar: ^1.12.30
  rxdart: ^0.28.0
  shimmer: ^3.0.0
  timeago: ^3.7.1
  intl: ^0.20.2
  provider: ^6.1.5
  auto_size_text: ^3.0.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.5
  flutter_confetti: ^0.5.1
  mobile_scanner: <7.0.1
  image_picker: ^1.1.2
  uuid: ^4.5.1
  flutter_typeahead:
    git:
      url: https://github.com/breez/flutter_typeahead.git
      ref: 4a494322762af9f30820f3c63aba784d46b86b69

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gifs/
    - assets/images/tiled/
    - assets/images/items/
    - assets/images/joystick/
    - assets/images/player/
    - assets/images/npc/
    - assets/images/interface/
    - assets/images/enemy/muddy/
    - assets/images/enemy/swampy/
    - assets/images/
    - assets/audio/
    - assets/legends/
    - assets/3d_icons/
